- README.md
the function getCorrelationContext() throw undefined error , update readme to use getCorrelationObject() instead .
> wrong function name

- README.md
- cf-nodejs-logging-support-core/log-core.js
- test/test-core.js
Hey everyone,
as described in #51, it was not possible to set and get the tenant_id property. I added two functions to enhance this behavior.
If you have any enhancements for me, let me know😁 
BR Robert 
PS.: At least for me there is one failing test which was there before. Not sure about that one.
> Add functions to set and get the tenant_id

- cf-nodejs-logging-support-core/log-core.js
- config.js
- sample/cf-nodejs-shoutboard/package-lock.json
- sample/cf-nodejs-shoutboard/package.json
- sample/cf-nodejs-shoutboard/web-express.js
- test/exp-results.js
- test/test-core.js
- Added tenant_subdomain field and setter/getter
> Add tenant_subdomain

- index.js
- logger/log-connect.js
- test/test-index.js
- test/test-log-connect.js
This PR adds support for the [Connect](https://www.npmjs.com/package/connect) server framework.
Co-authored-by: Nicklas Dohrn <nicklas.dohrn@sap.com>
> Add support for Connect server framework

- README.md
- config.js
- core/log-core.js
- index.js
- logger/log-connect.js
- logger/log-express.js
- logger/log-plainhttp.js
- logger/log-restify.js
- test/allbranchconfig.js
- test/test-log-connect.js
- test/test-log-express.js
- test/test-log-plainhttp.js
- test/test-log-restify.js
Adds functionality to set request logging level globally
> Add functionality to set log level for all request logs

- CONTRIBUTING.md
- LICENSE
- LICENSES/Apache-2.0.txt
- README.md
- package.json
- Fixed license text, updated using reuse tool
- Add CONTRIBUTION.md - no custom rules yet
- Add requirements and licensing sections to README.md <-- please review
- Aligned engine version in package.json with minimum version in CI config (v8.0)
> Compliance fix

- .travis.yml
- README.md
- migration to travis-ci.com is done --> this PR is also a test for travis config for PRs
- update .travis.yml to
- to include minimum, latest and LTS Node.js versions
- limit ci test to master branch and PRs to master branch
- update badges in README.md
> Migrate Travis CI

- config.js
- core/log-core.js
- package-lock.json
- package.json
- sample/cf-nodejs-shoutboard/package-lock.json
- sample/cf-nodejs-shoutboard/package.json
- sample/winston-sample/package-lock.json
- sample/winston-sample/package.json
- test/allbranchconfig.js
- test/test-core.js
- Update [uuid](https://www.npmjs.com/package/uuid) to v8.3.2 to fix known issue with Math.random() fallback ([related comment](https://github.com/uuidjs/uuid/issues/531#issuecomment-831938231)).
- Update dependencies.
- Fix typo.
> Update UUID version and dependencies

- core/log-core.js
> Check for self references in recursive functions

- docs/advanced-usage/04-dynamic-logging-level-threshold.md
- Add command and description to generate key-pair with correct format.
- Provide commands and description required to use token-creator tool
- Minor changes and format fixes.
> Rework docs on dynamic logging level threshold

- package-lock.json
- package.json
- update indirect dependencies
- change version to 6.13.0
> Prepare release v6.13.0

- core/log-core.js
- test/test-core.js
* Enable correct format for custom fields when binding to multiple logging services.
> Fix binding detection

- v2/cf-nodejs-logging-support/package.json
- v2/cf-nodejs-logging-support/src/lib/config/config-cf.json
- v2/cf-nodejs-logging-support/src/lib/config/config-core.json
- v2/cf-nodejs-logging-support/src/lib/config/config-request.json
- v2/cf-nodejs-logging-support/src/lib/config/config-sap-passport.json
- v2/cf-nodejs-logging-support/src/lib/config/config-schema.json
- v2/cf-nodejs-logging-support/src/lib/config/config.ts
- v2/cf-nodejs-logging-support/src/lib/config/interfaces.ts
- v2/cf-nodejs-logging-support/src/lib/logger/logger.ts
- v2/cf-nodejs-logging-support/src/lib/logger/record-factory.ts
- v2/cf-nodejs-logging-support/src/lib/logger/root-logger.ts
- v2/cf-nodejs-logging-support/src/lib/logger/source-utils.ts
- v2/cf-nodejs-logging-support/src/lib/middleware/framework-services/connect.ts
- v2/cf-nodejs-logging-support/src/lib/middleware/framework-services/express.ts
- v2/cf-nodejs-logging-support/src/lib/middleware/framework-services/plainhttp.ts
- v2/cf-nodejs-logging-support/src/lib/middleware/framework-services/restify.ts
- v2/cf-nodejs-logging-support/src/performance-test/config-cf-with-defaults.json
- v2/cf-nodejs-logging-support/src/performance-test/config-request-with-defaults.json
- v2/cf-nodejs-logging-support/src/test/acceptance-test/child-logger.test.js
- v2/cf-nodejs-logging-support/src/test/acceptance-test/config.test.js
- v2/cf-nodejs-logging-support/src/test/acceptance-test/global-context.test.js
- v2/cf-nodejs-logging-support/src/test/config-test.json
- v2/cf-nodejs-logging-support/src/test/unit-test/config.test.js
Some small improvements and fixes.
> Force errors and fix

- v2/cf-nodejs-logging-support/src/lib/logger/logger.ts
Keep registered fields consistent between different logger instances.
> keep registered fields consistent

- package-lock.json
- package.json
- src/lib/config/config-validator.ts
- src/lib/logger/cache.ts
- src/lib/logger/context.ts
- src/lib/logger/record-factory.ts
- src/lib/logger/source-utils.ts
- src/lib/middleware/middleware.ts
- src/test/acceptance-test/restify/app.js
- AJV: turn strict mode off to avoid startup message.
- Fix field `response_time_ms`.
- Install server framework as `devDependencies` for acceptance-test.
- Delete stringify of config fields.
> Beta fixes

- package-lock.json
- package.json
- sample/cf-nodejs-logging-support-sample/package-lock.json
- sample/cf-nodejs-logging-support-sample/package.json
- sample/cf-nodejs-shoutboard/package-lock.json
- sample/cf-nodejs-shoutboard/package.json
- sample/winston-sample/package-lock.json
- sample/winston-sample/package.json
- test/test-core.js
* Update dependencies in library and samples
* Fixed tests
* Set supported engine to > 12
* Set version to 6.14.1 (patch release)
> Prepare patch update v6.14.1

- docs/advanced-usage/04-dynamic-logging-level-threshold.md
- docs/configuration/custom-fields-format.md
- docs/configuration/default-req-log-level.md
- docs/configuration/fields.md
- docs/configuration/introduction.md
- docs/general-usage/04-custom-fields.md
- docs/index.markdown
- docs/migration.md
**Note: Base branch is "main". This will be the new default branch when we release v7.**
- Add migration guide
- Improve documentations, i.e. fields configuration
> Add v7 migration guide and improve documentation

- sample/cf-nodejs-logging-support-sample/app.js
- sample/cf-nodejs-logging-support-sample/public/index.html
- sample/cf-nodejs-logging-support-sample/public/scripts/logic.js
- sample/cf-nodejs-logging-support-sample/public/styles/style.css
This changes and adds two main features:
- The last sent log message is now shown in the Client UI
- The currently active service bindings are listed in the UI
> Update sample app with new features

- package.json
Use entry point path for `module` field.
> Fix module path in package.json

- docs/Gemfile.lock
- docs/_config.yml
- docs/_sass/custom/custom.scss
- docs/configuration/fields.md
- docs/configuration/framework.md
- docs/getting-started/01-installation.md
- docs/getting-started/02-framework-samples.md
- package-lock.json
- package.json
- src/lib/config/default/config-request.json
- src/lib/config/default/config-schema.json
- src/lib/config/interfaces.ts
- src/lib/middleware/framework-services/connect.ts
- src/lib/middleware/framework-services/express.ts
- src/lib/middleware/framework-services/fastify.ts
- src/lib/middleware/framework-services/plainhttp.ts
- src/lib/middleware/framework-services/restify.ts
- src/lib/middleware/interfaces.ts
- src/lib/middleware/middleware.ts
- src/lib/middleware/requestAccessor.ts
- src/lib/middleware/responseAccessor.ts
- src/lib/middleware/utils.ts
- src/test/acceptance-test/fastify/app.js
- src/test/acceptance-test/request-context.test.js
- src/test/unit-test/config.test.js
- Add middleware for [Fastify](https://fastify.dev/)
- Add/update tests
- Update documentation and framework samples
- Fix documentation title and copyright note
> Add fastify middleware
